groupings:
  carriers:
    "H$_2$ infrastructure":
      - H2
      - H2 Store
      - ammonia cracker
      - H2 pipeline
    "H$_2$ reforming":
      - Methanol steam reforming
      - Methanol steam reforming CC
      - SMR
      - SMR CC
    "battery storage":
      - battery
      - home battery
      - home battery charger
      - battery charger
      - home battery discharger
      - battery discharger
      - Battery Storage
      - EV battery
    biomass-to-liquid:
      - biomass to liquid
      - biomass to liquid CC
    biomass-to-methanol:
      - biomass-to-methanol
      - biomass-to-methanol CC
      - enhanced-biomass-to-methanol
    biomass-to-industry:
      - solid biomass for industry heat
      - solid biomass for industry heat CC
    biomass-to-heat:
      - biomass boiler
      - rural biomass boiler
      - urban decentral biomass boiler
    biomass:
      - solid biomass
      - municipal solid waste
    biogas:
      - biogas
    biogas-to-methanol:
      - biogas-to-methanol
      - biogas-to-methanol CC
    biomass-to-gas:
      - biogas to gas
      - biogas to gas CC
      - BioSNG
      - BioSNG CC
    "carbon capture":
      - co2 stored
      - DAC
    CO$_2$:
      - co2
    "CO$_2$ sequestered":
      - co2 sequestered
    "electricity demand":
      - low voltage
      - electricity for industry heat
      - industry electricity
      - electricity
      - agriculture electricity
      - electricity distribution grid
    ammonia:
      - NH3
      - ammonia store
    methanol:
      - methanol
      - methanol transport
    "oil store":
      - oil
    "gas store":
      - gas
    "fossil imports":
      - oil primary import
      - gas import
      - oil primary refining
    "green imports":
      - methanol import
      - ammonia import
      - H2 import
      - FT import
      - FT refining
    "gas infrastructure":
      - gas pipeline new
      - gas pipeline
      - CO2 pipeline
    "H$_2$-to-power/heat":
      - H2 turbine
      - H2 Fuel Cell
      - urban central H2 CHP
    "gas-to-power/heat":
      - OCGT
      - urban central gas CHP
      - urban central gas CHP CC
    "biomass-to-power/heat":
      - urban central solid biomass CHP
      - urban central solid biomass CHP CC
      - waste CHP
      - waste CHP CC
    "gas-to-heat":
      - rural gas boiler
      - urban central gas boiler
      - urban decentral gas boiler
    "industry heat":
      - gas for industry heat
      - gas for industry heat CC
      - methanol for industry heat
      - methanol for industry heat CC
      - H2 for industry heat
    "heat demand":
      - urban central heat
      - rural heat
      - agriculture heat
      - urban decentral heat
      - low-temperature heat for industry
    "heat storage":
      - urban decentral water tanks
      - urban decentral water tanks charger
      - urban decentral water tanks discharger
      - urban central water tanks
      - urban central water tanks charger
      - urban central water tanks discharger
      - rural water tanks
      - rural water tanks charger
      - rural water tanks discharger
    "methanol demand":
      - industry methanol
      - shipping methanol
      - methanol-to-gasoline
      - methanol-to-olefins/aromatics
      - methanol-to-kerosene
    "oil demand":
      - naphtha
      - naphtha-to-HVC
      - naphtha for industry
      - kerosene refined
      - kerosene
      - shipping oil
      - oil-to-kerosene
    "hydrocarbons demand":
      - agriculture machinery oil
      - HVC for industry
    "transport demand":
      - shipping
      - kerosene for aviation
      - land transport EV
      - BEV charger
      - V2G
    hydro:
      - hydro
      - PHS
      - ror
      - Reservoir & Dam
    "hydrogen demand":
      - H2 for industry
    landfill:
      - non-sequestered HVC
      - HVC to air
    "fossil methanol":
      - grey methanol
      - blue methanol
    "methanol-to-power/heat":
      - OCGT methanol
      - allam methanol
      - CCGT methanol CC
      - CCGT methanol
      - urban central methanol CHP
      - urban central methanol CHP CC
    "offshore wind":
      - offwind-dc
      - offwind-ac
      - offwind-float
    "onshore wind":
      - onwind
    "H$_2$ electrolysis":
      - H2 Electrolysis
    methanation:
      - Sabatier
    power-to-heat:
      - heat pump
      - rural air heat pump
      - urban decentral resistive heater
      - rural ground heat pump
      - rural resistive heater
      - urban decentral air heat pump
      - urban central air heat pump
      - urban central resistive heater
    power-to-liquid:
      - methanolisation
      - Fischer-Tropsch
      - Haber-Bosch
    process emissions:
      - process emissions
      - process emissions CC
    solar:
      - solar
      - solar-hsat
      - urban central solar thermal
      - rural solar thermal
      - urban decentral solar thermal
      - solar rooftop
    "transmission infrastructure":
      - AC
      - DC
    "steel":
      - DRI
      - HBI
      - steel
      - EAF
    "oil cracking":
      - oil cracking

  generation:
    "dispatchable generation":
      - urban central gas CHP
      - urban central gas CHP CC
      - allam
      - OCGT
      - OCGT methanol
      - allam methanol
      - CCGT methanol CC
      - CCGT methanol
      - urban central methanol CHP
      - urban central methanol CHP CC
      - urban central solid biomass CHP
      - urban central solid biomass CHP CC
      - H2 turbine
      - H2 Fuel Cell
      - urban central H2 CHP
    "non-dispatchable generation":
      - waste CHP CC
      - waste CHP
    "renewables":
      - solar
      - solar-hsat
      - hydro
      - PHS
      - onwind
      - offwind-dc
      - offwind-ac
      - offwind-float
      - urban central solar thermal
      - rural solar thermal
      - urban decentral solar thermal
      - ror
    "import/export":
      - AC
      - DC
    "industry demand":
      - DRI
      - EAF
      - DAC
      - methanol-to-olefins/aromatics
      - Haber-Bosch
    "methanol production":
      - methanolisation
      - biogas-to-methanol
      - biogas-to-methanol CC
    "hydrogen production":
      - H2 Electrolysis
    "battery storage":
      - battery discharger
      - battery charger
    "electricity demand":
      - electricity distribution grid

  cost:
    H$_2$:
      - H2
      - H2 Store
      - ammonia cracker
      - H2 pipeline
      - SMR
      - H2 Electrolysis
      - H2 turbine
      - H2 for industry heat
      - H2 Fuel Cell
      - urban central H2 CHP
      - H2 for industry
      - solid biomass to hydrogen
      - Methanol steam reforming
      - SMR CC
      - Methanol steam reforming CC
    methanol:
      - blue methanol
      - grey methanol
      - methanol
      - biomass-to-methanol
      - biogas-to-methanol
      - OCGT methanol
      - allam methanol
      - CCGT methanol
      - methanol transport
      - methanolisation
      - methanol for industry heat
      - urban central methanol CHP
      - methanol-to-gasoline
      - methanol-to-olefins/aromatics
      - methanol-to-kerosene
      - shipping methanol
      - biomass-to-methanol CC
      - biogas-to-methanol CC
      - CCGT methanol CC
      - methanol for industry heat CC
      - urban central methanol CHP CC
    biomass:
      - solid biomass
      - solid biomass for industry heat
      - biomass boiler
      - rural biomass boiler
      - urban decentral biomass boiler
      - municipal solid waste
      - biogas
      - urban central solid biomass CHP
      - waste CHP
      - urban central solid biomass CHP CC
      - solid biomass for industry heat CC
      - waste CHP CC
    renewables:
      - solar rooftop
      - solar
      - solar-hsat
      - hydro
      - PHS    
      - onwind
      - offwind-dc
      - offwind-ac
      - offwind-float
      - urban central solar thermal
      - rural solar thermal
      - urban decentral solar thermal
      - ror
    electrification:
      - low voltage
      - DC
      - AC
      - battery
      - Battery Storage
      - EV battery
      - home battery
      - land transport EV
      - V2G
      - home    
      - DC battery charger
      - battery charger
      - home battery discharger
      - battery discharger
      - BEV charger
      - industry electricity
      - electricity distribution grid
      - heat pump
      - rural air heat pump
      - urban decentral resistive heater
      - rural ground heat pump
      - rural resistive heater
      - urban decentral air heat pump
      - urban central air heat pump
      - urban central resistive heater
      - electricity for industry heat
    ammonia:
      - NH3
      - ammonia store
      - Haber-Bosch
    "oil imports":
      - oil primary import
      - oil primary refining
    "methane imports":
      - gas import
    "green imports":
      - FT import
      - methanol import
      - ammonia import
      - H2 import
      - FT refining
    CO$_2$:
      - co2 stored
      - DAC
      - co2
      - co2 sequestered
      - CO2 pipeline
      - process emissions
      - process emissions CC
    oil:
      - biomass to liquid
      - biomass to liquid CC
      - oil
      - Fischer-Tropsch
      - naphtha-to-HVC
      - naphtha for industry
      - agriculture machinery oil
      - kerosene
      - oil-to-kerosene
      - kerosene refined
    methane:
      - gas
      - BioSNG
      - biogas to gas
      - gas pipeline new
      - gas pipeline
      - urban central gas CHP
      - OCGT
      - rural gas boiler
      - urban central gas boiler
      - urban decentral gas boiler
      - gas for industry heat
      - Sabatier
      - BioSNG CC
      - biogas to gas CC
      - gas for industry heat CC
      - urban central gas CHP CC
    thermal storage:
      - urban decentral water tanks
      - urban decentral water tanks charger
      - urban decentral water tanks discharger
      - urban central water tanks
      - urban central water tanks charger
      - urban central water tanks discharger
      - rural water tanks
      - rural water tanks charger
      - rural water tanks discharger
    # demands
    steel:
      - steel
      - DRI
      - HBI
      - EAF
    electricity:
      - electricity
      - agriculture electricity
      - industry electricity
      - land transport EV
    "industry heat":
      - high heat for industry
      - medium heat for industry
      - low heat for industry
      - agriculture heat
    "residential heat":
      - urban central heat
      - rural heat
      - urban decentral heat
    "aviation":
      - kerosene for aviation
    "shipping":
      - shipping
    "industry feedstock":
      - HVC for industry
      - industry methanol

  demand_bus_carriers:
    H$_2$:
      - H2
    high value chemicals:
      - HVC for industry
    electricity:
      - low voltage
    industry heat:
      - agriculture heat
      - low-temperature heat for industry
      - high heat for industry
      - medium heat for industry
    residential heat:
      - urban decentral heat
      - urban central heat
      - rural heat
    road:
      - EV battery
    aviation:
      - aviation
    shipping:
      - shipping
    other demands:
      - NH3
      - agriculture machinery oil
      - industry methanol
      - steel

  demand_carriers:
    H$_2$ for industry:
      - H2 for industry
    high value chemicals:
      - HVC for industry
    ammonia:
      - NH3
    residential electricity:
      - electricity
    industry electricity:
      - agriculture electricity
      - industry electricity
    industry heat:
      - agriculture heat
      - low-temperature heat for industry
      - high heat for industry
      - medium heat for industry
      - low heat for industry
    residential heat:
      - rural heat
      - urban decentral heat
      - urban central heat
    transport demand:
      - aviation
      - shipping
      - land transport EV
    other demands:
      - agriculture machinery oil
      - industry methanol
      - steel
    
  supply_carriers:
    electricity:
      - 'electricity'
      - 'BEV charger'
      - 'DAC'
      - 'EAF'
      - 'V2G'
      - 'aviation electrified'
      - 'shipping electrified'
      - 'electricity distribution grid'
      - 'electricity for industry heat'
      - 'home battery charger'
      - 'home battery discharger'
      - 'methanolisation'
      - 'rural air heat pump'
      - 'rural ground heat pump'
      - 'rural resistive heater'
      - 'urban central air heat pump'
      - 'EV battery'
      - 'urban central resistive heater'
      - 'urban decentral air heat pump'
      - 'solar rooftop'
      - 'urban decentral resistive heater'
    hydrogen:
      - 'H2'
      - 'H2 Fuel Cell'
      - 'H2 for industry heat'
      - 'H2 pipeline'
      - 'H2 turbine'
      - 'DRI'
      - 'urban central H2 CHP'
      - 'H2 Store'
      - 'H2 for industry'
    methanol:
      - 'methanol'
      - 'Methanol steam reforming'
      - 'Methanol steam reforming CC'
      - 'methanol for industry heat'
      - 'methanol for industry heat CC'
      - 'methanol-to-gasoline'
      - 'methanol-to-kerosene'
      - 'methanol-to-olefins/aromatics'
      - 'shipping methanol'
      - 'urban central methanol CHP'
      - 'urban central methanol CHP CC'
      - 'industry methanol'
    gas:
      - 'gas'
      - 'SMR'
      - 'SMR CC'
      - 'gas for industry heat'
      - 'gas for industry heat CC'
      - 'rural gas boiler'
      - 'urban central gas CHP'
      - 'urban central gas CHP CC'
      - 'urban central gas boiler'
      - 'urban decentral gas boiler'
    oil:
      - 'oil'
      - 'agriculture machinery oil'
      - 'naphtha-to-HVC'
      - 'oil-to-kerosene'
      - 'shipping oil'
    ammonia:
      - 'ammonia cracker'
      - 'ammonia store'
    biomass:
      - 'biomass'
      - 'rural biomass boiler'
      - 'solid biomass for industry heat'
      - 'solid biomass for industry heat CC'
      - 'solid biomass to hydrogen'
      - 'urban central solid biomass CHP'
      - 'urban central solid biomass CHP CC'
      - 'urban decentral biomass boiler'
    waste heat: 
      - 'waste CHP'
      - 'waste CHP CC'
    excess heat:
      - 'Haber-Bosch'
      - 'methanolisation' 
      - 'Sabatier'
      - 'Fischer-Tropsch'
      - 'H2 Electrolysis'
    water tank:
      - urban central water tanks discharger
      - urban central water tanks charger
      - urban decentral water tanks discharger
      - urban decentral water tanks charger

    
    renewable heat:
      - 'rural solar thermal'
      - 'urban central solar thermal'
      - 'urban decentral solar thermal'

  LCOE_carrier:
    electricity:
      - low voltage
      - AC
    hydrogen:
      - H2
    diesel:
      - oil
    kerosene:
      - kerosene
    naphtha:
      - naphtha
    biomass:
      - solid biomass
      - biomass-to-methanol CC
      - biomass-to-methanol
    biogas:
      - biogas
      - biogas-to-methanol
      - biogas-to-methanol CC
    "CO$_2$":
      - co2
      - non-sequestered HVC
      - co2 stored
      - process emissions
    heat:
      - urban central heat
    methanol:
      - methanol

  LCOE_technologies:
    industry heat electrified:
      - electricity for industry heat
    industry heat methanol:
      - methanol for industry heat
    industry heat biomass:
      - solid biomass for industry heat
    industry heat gas:
      - gas for industry heat
    industry heat hydrogen:
      - hydrogen for industry heat
    aviation electrified:
      - aviation electrified
    aviation methanol:
      - methanol-to-kerosene
    aviation oil:
      - oil-to-kerosene
    shipping electrified:
      - shipping electrified
    shipping methanol:
      - shipping methanol
    shipping oil:
      - shipping oil
    high value chemicals methanol:
      - methanol-to-olefins/aromatics
    high value chemicals oil:
     - naphtha-to-HVC

  load_carrier_groups:
    residential electricity:
      - electricity
    industry electricity:
      - industry electricity
      - agriculture electricity
    transport:
      - land transport EV
      - shipping
      - aviation
    industry heat:
      - low heat for industry
      - medium heat for industry
      - high heat for industry
      - agriculture heat
    residential heat:
      - rural heat
      - urban decentral heat
      - urban central heat
    steel:
      - steel
    other industry demands:
      - agriculture machinery oil
      - industry methanol
      - NH3
      - ammonia
      - HVC for industry
  
  balance_map:
    backup:
      - OCGT methanol
      - allam methanol