pcipmi:
  carrier_networks:
    CO2:
      enable: true
      include:
        greenfield: false
        pcipmi: true
      extendable:
        greenfield: []
        pcipmi: []
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: true
      include:
        greenfield: false
        pcipmi: true
      extendable:
        greenfield: []
        pcipmi: []
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: true
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0

pcipmi-nat:
  carrier_networks:
    CO2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ["national"]
        pcipmi: []
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ["national"]
        pcipmi: []
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: true
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0

pcipmi-internat:
  carrier_networks:
    CO2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ["national", "international"]
        pcipmi: []
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ["national", "international"]
        pcipmi: []
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: true
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0

decentral-islands:
  carrier_networks:
    CO2:
      enable: false
    H2:
      enable: false
      
  pcipmi_projects:
    enable: false
    include: 
      - storage_units_electricity
    options:
      delay: 0

central-planning:
  carrier_networks:
    CO2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ["national", "international"]
        pcipmi: ["national", "international"]
      p_nom_max: .inf
      options:
        cost_factor: 1.0
        length_factor: 1.0
        delay: 0
    H2:
      enable: true
      include:
        greenfield: true
        pcipmi: true
      extendable:
        greenfield: ["national", "international"]
        pcipmi: ["national", "international"]
      p_nom_max: .inf
      options:
        delay: 0
      
  pcipmi_projects:
    enable: true
    include: 
      - storage_units_electricity
      - stores_co2
      - stores_h2
    options:
      delay: 0