# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
version: v2025.01.0
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

remote:
  ssh: z1
  path: scratch/projects/pcipmi-policy-targets/workflow/pypsa-eur-resilient

# PCI-PMI policy paper settings
pcipmi_policy_paper:
  co2_sequestration_min_mt:
    enable: true
    targets:
      2030: 50
      2040: 150
      2050: 250 # https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52024DC0062
  h2_production_min_mt:
    enable: true
    targets:
      2030: 10
      2040: 27.5
      2050: 45 # https://www.isi.fraunhofer.de/en/blog/2023/europa-energiesystem-2050-wasserstoff-industrie.html
  electrolyser_capacity_min_gw:
    enable: true
    targets:
      2030: 40
      2040: 110 # proportional based on 2030
      2050: 180 # proportional based on 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: "second-run"
  name:
  - pcipmi
  - pcipmi-delay-10years
  - pcipmi-national-expansion
  - pcipmi-national-international-expansion
  - no-pipelines
  - greenfield-pipelines
  scenarios:
    enable: true
    file: config/second-run.scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: true # Set to false if problems regarding missing directories occur

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# Solve two-step operations
solve_operations:
  resample_temporal_resolution: false
  columns:
    - ops___ghg_target___stranded_invest
    - ops___ghg_h2_target___no_pipes_short_term_invest
    - ops___emission_price_h2_target___no_pipes_short_term_invest
  definitions:
    ops___ghg_target___stranded_invest:
      options:
        allow_load_shedding: false
        allow_investments: false # all assets except for pipelines
        fix_all_capacities: true # ["Generator", "Line", "Link", "Store"]
        fix_optimal_pipeline_capacities: true # CO2 and H2 pipelines
        remove_co2_pipelines: false
        remove_h2_pipelines: false
        remove_co2_sequestration: false
        use_emission_price: false
      overwrite_config:
        pcipmi_policy_paper:
          co2_sequestration_min_mt:
            enable: false
          h2_production_min_mt:
            enable: false
          electrolyser_capacity_min_gw:
            enable: false
    ops___ghg_h2_target___no_pipes_short_term_invest:
      options:
        allow_load_shedding: 10000 # EUR/MWh
        allow_investments: true # all assets except for pipelines
        fix_all_capacities: false # ["Generator", "Line", "Link", "Store"]
        fix_optimal_pipeline_capacities: true # CO2 and H2 pipelines
        remove_co2_pipelines: true
        remove_h2_pipelines: true
        remove_co2_sequestration: true
        use_emission_price: false
      overwrite_config:
        pcipmi_policy_paper:
          co2_sequestration_min_mt:
            enable: false
          h2_production_min_mt:
            enable: true
          electrolyser_capacity_min_gw:
            enable: false
    ops___emission_price_h2_target___no_pipes_short_term_invest:
      options:
        allow_load_shedding: 10000 # EUR/MWh
        allow_investments: true # all assets except for pipelines
        fix_all_capacities: false # ["Generator", "Line", "Link", "Store"]
        fix_optimal_pipeline_capacities: true # CO2 and H2 pipelines
        remove_co2_pipelines: true
        remove_h2_pipelines: true
        remove_co2_sequestration: true
        use_emission_price: true
      overwrite_config:
        pcipmi_policy_paper:
          co2_sequestration_min_mt:
            enable: false
          h2_production_min_mt:
            enable: true
          electrolyser_capacity_min_gw:
            enable: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - 70
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: enable

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
  transmission_limit: v1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  enable: true
  include:
    pcipmi: true
    tyndp2020: false
    nep: false
    manual: false
  skip:
  - upgraded_lines
  - upgraded_links
  status:
    pcipmi: ['under_construction', 'in_permitting', 'confirmed', 'planned_not_yet_permitted', 'under_consideration']
    tyndp2020: ['under_construction', 'in_permitting', 'confirmed']
    nep: ['under_construction', 'in_permitting', 'confirmed']
  new_link_capacity: keep # keep or zero

carrier_networks:
  CO2:
    enable: true
    include:
      greenfield: true
      pcipmi: true
    extendable:
      greenfield: ['national', 'international']
      pcipmi: []
    p_nom_max: .inf
    options:
      cost_factor: 1.0
      length_factor: 1.0
      delay: 0
  H2:
    enable: true
    include:
      greenfield: true
      pcipmi: true
    extendable:
      greenfield: ['national', 'international']
      pcipmi: []
    p_nom_max: .inf
    options:
      delay: 0

pcipmi_projects:
  enable: true
  include:
    - storage_units_electricity
    - stores_co2
    - stores_h2
  options:
    delay: 0

existing_capacities:
  grouping_years_power: [1920, 1950, 1955, 1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # heat grouping years >= baseyear will be ignored

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  shipping: true
  aviation: true
  agriculture: true
  fossil_fuels: true
  SMR: true
  SMR_cc: true
  regional_oil_demand: true
  regional_coal_demand: false
  regional_co2_sequestration_potential:
    enable: true
    attribute:
    - conservative estimate GAS Mt
    - conservative estimate OIL Mt
    include_onshore: false
    min_size: 3
    max_size: .inf # 25
    years_of_storage: 25
  co2_sequestration_potential:
    2020: 0
    2025: 0
    2030: 400
    2035: 400
    2040: 400
    2045: 400
    2050: 400
  co2_sequestration_cost: 10
  co2_sequestration_lifetime: 50
  co2_spatial: true
  gas_network: false
  H2_retrofit: false
  H2_retrofit_capacity_per_CH4: 0.6
  gas_network_connectivity_upgrade: 1
  gas_distribution_grid: true
  gas_distribution_grid_cost_factor: 1.0
  biomass_spatial: true
  biomass_transport: false
  biogas_upgrading_cc: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  mode: custom_busmap
  administrative:
    level: 1
    DK: 2
    FI: 2
    'NO': 2
    SE: 2
    BA: 0
    BG: 0
    GB: 1
    HR: 0
    RO: 0
    RS: 0
    XK: 0
  focus_weights:
    FI: 0.05
    'NO': 0.05
    PL: 0.07
    SE: 0.05
  temporal:
    resolution_elec: false
    resolution_sector: 2190seg

solving:
  mem_mb: 180000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  memory_logging_frequency: 30 # in seconds
  runtime: 40h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/
  options:
    assign_all_duals: true
    custom_extra_functionality: false # Has to be set to false, otherwise the imported solve_network function will not work correctly
    noisy_costs: true

plotting:
  balance_map:
    bus_carriers:
    - AC
    - H2
    - co2_stored
    AC:
      unit: TWh
      unit_conversion: 1_000_000
      cmap: Greens
      vmin:
      vmax:
      region_unit: €/MWh
      bus_factor: 0.002
      branch_factor: 0.15
      flow_factor: 100
      bus_sizes:
      - 200
      - 100
      branch_sizes:
      - 200
      - 100
    H2:
      unit: TWh
      unit_conversion: 1_000_000
      cmap: Blues
      vmin: 50
      vmax: 100
      region_unit: €/MWh
      bus_factor: 0.002
      branch_factor: 0.06
      flow_factor: 25
      bus_sizes:
      - 50
      - 25
      branch_sizes:
      - 40
      - 20
    co2_stored:
      unit: Mt
      unit_conversion: 1_000_000
      cmap: Purples
      vmin:
      vmax:
      region_unit: €/t_${CO_2}$
      bus_factor: 0.03
      branch_factor: 0.1
      flow_factor: 45
      bus_sizes:
      - 50
      - 10
      branch_sizes:
      - 5
      - 2
  capacity_map:
    H2:
      unit: TW
      unit_conversion: 1_000_000
      cmap: Blues
      vmin: 50
      vmax: 100
      region_unit: €/MWh
      bus_factor: 0.002
      branch_factor: 0.0003
      flow_factor: 45
      bus_sizes:
      - 50
      - 25
      branch_sizes:
      - 40
      - 20
    co2 stored:
      unit: Mt
      unit_conversion: 1_000_000
      cmap: Purples
      vmin:
      vmax:
      region_unit: €/t_${CO_2}$
      bus_factor: 200
      branch_factor: 0.001
      flow_factor: 150
      bus_sizes:
      - 0.005
      - 0.001
      branch_sizes:
      - 5
      - 2
